Vagrant.configure("2") do |config|
  config.vm.box = "kaorimatz/archlinux-x86_64"
  config.vm.hostname = "jackmarshall-tournaments"
  config.vm.synced_folder ".", "/home/vagrant/src/git.elwinar.com/jackmarshall/tournaments"
  config.vm.provision :shell, path: "provision.sh"
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
end
